/* Database schema to keep the structure of entire database. */

CREATE DATABASE HOSPITAL;

DROP TABLE IF EXISTS PATIENTS;

CREATE TABLE PATIENTS(
	ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(120),
	DATE_OF_BIRTH DATE,
	PRIMARY KEY (ID)
)

DROP TABLE IF EXISTS TREATMENTS;

CREATE TABLE TREATMENTS (
 	ID INT GENERATED ALWAYS AS IDENTITY,
	TYPE VARCHAR(120),
	NAME VARCHAR(120),
	PRIMARY KEY (ID)
)

DROP TABLE IF EXISTS MEDICAL_HISTORIES;

CREATE TABLE MEDICAL_HISTORIES (
	ID INT GENERATED ALWAYS AS IDENTITY,
	ADMITTED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
	PATIENT_ID INT,
	STATUS VARCHAR(120),
	FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID)
)

ALTER TABLE MEDICAL_HISTORIES
ADD CONSTRAINT MEDICAL_HISTORIES_PKEY PRIMARY KEY (ID);


DROP TABLE IF EXISTS MEDICAL_HISTORIES_TREATMENT;

CREATE TABLE MEDICAL_HISTORIES_TREATMENT(
	TREATMENT_ID INT REFERENCES TREATMENTS (ID),
	MEDICAL_HISTORY_ID INT 	REFERENCES MEDICAL_HISTORIES (ID)	
) 

DROP TABLE IF EXISTS INVOICES;

CREATE TABLE INVOICES (
	ID INT GENERATED ALWAYS AS IDENTITY,
	TOTAL_AMOUNT DECIMAL,
	GENERATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PAYED_AT TIMESTAMP,
	MEDICAL_HISTORY_ID INT UNIQUE REFERENCES MEDICAL_HISTORIES (ID),
	PRIMARY KEY (ID)
)

DROP TABLE IF EXISTS INVOICE_ITEMS;

CREATE TABLE INVOICE_ITEMS (
	ID INT GENERATED ALWAYS AS IDENTITY,
	UNIT_PRICE DECIMAL,
	QUANTITY INT,
	TOTAL_PRICE DECIMAL,
	INVOICE_ID INT REFERENCES INVOICES (ID),
	TREATMENT_ID INT REFERENCES TREATMENTS (ID),
	PRIMARY KEY (ID)
)